services:
  coffeeguard:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - MODEL_PATH=models/coffeeguard_model.h5
    restart: unless-stopped

  coffeeguard2:
    build: .
    ports:
      - "8002:8000"
      - "8502:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - MODEL_PATH=models/coffeeguard_model.h5
    restart: unless-stopped
